version: '3.2'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
  graphql:
    environment:
      - MONGO_URI="mongodb://username:password@mongo:27017"
    depends_on:
      - mongo
    links:
      - mongo
